import { MandarineCore } from "https://deno.land/x/mandarinets/mod.ts";
import { MyController } from "./hello_world/helloWorld.ts";
const controllers = [MyController];
const services = [];
const middleware = [];
const repositories = [];
const configurations = [];
const components = [];
const otherModules = [];
new MandarineCore().MVC().run();
